from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
    path('', views.home, name='home'),
    url(r'^login/$', views.login, name='login'),
    url(r'^signup/$', views.register, name='signup'),
    url(r'^about/$', views.about, name='about'),
    url(r'^team/$', views.team, name='team'),
    url(r'^services/$', views.services, name='services'),
    url(r'^pricing/$', views.pricing, name='pricing'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^events/$', views.events, name='events'),
    url(r'^insights/$', views.blog, name='blog'),
    url(r'^blog1/$', views.blog1, name='blog1'),
    url(r'^blog2/$', views.blog2, name='blog2'),
    url(r'^blog3/$', views.blog3, name='blog3'),
    url(r'^blog4/$', views.blog4, name='blog4'),
    url(r'^gurugram/$', views.gurugram, name='gurugram'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^company/$', views.company, name='company'),
    url(r'^agent/$', views.agent, name='agent'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^pipeline/$', views.pipeline, name='pipeline'),
    url(r'^leads/$', views.leads, name='leads'),
    url(r'^opportunities/$', views.opportunities, name='opportunities'),
    url(r'^training/$', views.training, name='training'),
    url(r'^application/$', views.application, name='application'),
    url(r'^payments/$', views.payments, name='payments'),
    url(r'^helpcenter/$', views.helpCenter, name='helpcenter'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^addlead/$', views.addLead, name='addlead'),
    url(r'^addopportunities/$', views.addopportunities, name='addopportunities'),
    url(r'^addeditprofile/$', views.addeditprofile, name='addeditprofile'),
    url(r'^editprofile/$', views.editprofile, name='editprofile'),
    ]
