# Generated by Django 3.2 on 2021-05-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='contact',
            field=models.CharField(default=9090909999, max_length=255),
            preserve_default=False,
        ),
    ]
