# Generated by Django 3.2 on 2021-05-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0003_agent_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='contact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
