# Generated by Django 3.2 on 2021-06-13 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0005_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='opportunities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Targetindustries', models.CharField(max_length=255)),
                ('Companyindustry', models.CharField(max_length=255, null=True)),
                ('OpportunityLanguage', models.CharField(max_length=255)),
                ('Worldregions', models.CharField(max_length=255)),
                ('Countries', models.CharField(max_length=255)),
                ('Customertype', models.CharField(max_length=255)),
                ('Averagedealvalue', models.CharField(max_length=255)),
                ('Leadsprovided', models.CharField(max_length=255)),
                ('Specificlocation', models.CharField(max_length=255)),
                ('Products', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect_app.agent')),
            ],
        ),
    ]
