# Generated by Django 3.2 on 2021-06-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0007_auto_20210614_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='job_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
