# Generated by Django 3.2 on 2021-06-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0009_auto_20210615_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='editprofile',
        ),
    ]
