# Generated by Django 3.2 on 2021-07-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0010_delete_editprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='created_by',
        ),
        migrations.AddField(
            model_name='leads',
            name='created_by_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.agent'),
        ),
        migrations.AddField(
            model_name='leads',
            name='created_by_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.company'),
        ),
        migrations.DeleteModel(
            name='opportunities',
        ),
    ]
