# Generated by Django 3.2 on 2021-06-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0006_opportunities'),
    ]

    operations = [
        migrations.CreateModel(
            name='industries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='Companyindustry',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='Averagedealvalue',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='Countries',
            new_name='bussinesstype',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='Customertype',
            new_name='commission',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='Leadsprovided',
            new_name='industries',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='OpportunityLanguage',
            new_name='other',
        ),
        migrations.RemoveField(
            model_name='opportunities',
            name='Products',
        ),
        migrations.RemoveField(
            model_name='opportunities',
            name='Specificlocation',
        ),
        migrations.RemoveField(
            model_name='opportunities',
            name='Targetindustries',
        ),
        migrations.RemoveField(
            model_name='opportunities',
            name='Worldregions',
        ),
    ]
