# Generated by Django 3.2 on 2021-07-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0012_accreditation_agentdetails_companydetails_leadsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
