# Generated by Django 3.0.2 on 2021-09-27 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0013_leads_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='about_your_comp',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='facebook_page_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='short_summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='twitter_id',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FinancialTc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, null=True)),
                ('commission', models.CharField(max_length=255, null=True)),
                ('our_industry', models.CharField(max_length=255, null=True)),
                ('target_industories', models.CharField(max_length=255, null=True)),
                ('commission_details', models.CharField(max_length=255, null=True)),
                ('territories', models.CharField(max_length=255, null=True)),
                ('selling_method', models.CharField(max_length=255, null=True)),
                ('min_sales_experience_req', models.CharField(max_length=255, null=True)),
                ('industry_exp_req', models.CharField(max_length=255, null=True)),
                ('leads_provided', models.CharField(max_length=255, null=True)),
                ('avg_deal_value', models.CharField(max_length=255, null=True)),
                ('repeat_cast_spend', models.CharField(max_length=255, null=True)),
                ('exclusive_territory_avil', models.CharField(max_length=255, null=True)),
                ('available', models.CharField(max_length=255, null=True)),
                ('avg_sales_cycle', models.CharField(max_length=255, null=True)),
                ('payments_terms', models.CharField(max_length=255, null=True)),
                ('customer_type', models.CharField(max_length=255, null=True)),
                ('product_and_services', models.CharField(max_length=255, null=True)),
                ('about_the_opportunity', models.CharField(max_length=255, null=True)),
                ('why_self_employed_working_comp', models.TextField(max_length=255, null=True)),
                ('what_kind_self_empl_best_to_comp', models.TextField(max_length=255, null=True)),
                ('training_support', models.TextField(max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect_app.Company')),
            ],
        ),
    ]
