# Generated by Django 3.0.2 on 2021-09-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0014_auto_20210927_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtc',
            name='about_the_opportunity',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='financialtc',
            name='training_support',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='financialtc',
            name='what_kind_self_empl_best_to_comp',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='financialtc',
            name='why_self_employed_working_comp',
            field=models.TextField(max_length=2500, null=True),
        ),
    ]
