# Generated by Django 3.0.2 on 2021-10-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0015_auto_20210927_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_title', models.CharField(max_length=255, null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('Due_date', models.DateField(max_length=255, null=True)),
                ('leads', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.Leads')),
            ],
        ),
    ]
