# Generated by Django 3.0.2 on 2021-10-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0016_addtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=255, null=True)),
                ('lead_name', models.CharField(max_length=255, null=True)),
                ('Estimated_close', models.DateField(null=True)),
                ('Confidence', models.CharField(max_length=255, null=True)),
                ('leads', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.Leads')),
            ],
        ),
    ]
