# Generated by Django 3.0.2 on 2021-10-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0017_leadaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadaction',
            name='lead_name',
        ),
    ]
