# Generated by Django 3.0.2 on 2021-10-07 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0018_remove_leadaction_lead_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.Agent'),
        ),
        migrations.AddField(
            model_name='leadaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.Agent'),
        ),
    ]
