# Generated by Django 3.0.2 on 2021-10-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0019_auto_20211007_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtask',
            old_name='created_by',
            new_name='created_by_agent',
        ),
        migrations.RenameField(
            model_name='leadaction',
            old_name='created_by',
            new_name='created_by_agent',
        ),
        migrations.AddField(
            model_name='addtask',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leadaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
