# Generated by Django 3.0.2 on 2021-10-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0020_auto_20211007_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.Agent')),
                ('leads', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.Leads')),
            ],
        ),
        migrations.CreateModel(
            name='LeadContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.Agent')),
                ('leads', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.Leads')),
            ],
        ),
    ]
