# Generated by Django 3.0.2 on 2021-10-14 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0021_leadcontact_leadorganisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.Agent')),
                ('leads', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.Leads')),
            ],
        ),
    ]
