# Generated by Django 3.0.2 on 2021-10-14 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0022_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity', models.CharField(max_length=100, null=True)),
                ('Invoice_number', models.CharField(max_length=100, null=True)),
                ('business_name', models.CharField(max_length=100, null=True)),
                ('business_address', models.CharField(max_length=100, null=True)),
                ('business_address2', models.CharField(max_length=100, null=True)),
                ('business_city', models.CharField(max_length=100, null=True)),
                ('business_state', models.CharField(max_length=100, null=True)),
                ('business_country', models.CharField(max_length=100, null=True)),
                ('business_postal_code', models.CharField(max_length=100, null=True)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('comp_business_name', models.CharField(max_length=100)),
                ('comp_business_address', models.CharField(max_length=100)),
                ('comp_business_address2', models.CharField(max_length=100)),
                ('comp_business_city', models.CharField(max_length=100)),
                ('comp_business_sate', models.CharField(max_length=100)),
                ('comp_business_country', models.CharField(max_length=100)),
                ('comp_business_postal_code', models.CharField(max_length=100)),
                ('Currency', models.CharField(max_length=100)),
                ('Commission_percentage', models.CharField(max_length=100)),
                ('Invoice_due_date', models.DateField(auto_now_add=True, null=True)),
                ('Tax_name', models.CharField(max_length=100)),
                ('Tax_percentage', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.Agent')),
            ],
        ),
    ]
