# Generated by Django 3.2.8 on 2021-10-30 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0023_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=225, null=True)),
                ('discriptions', models.TextField(max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.companydetails')),
                ('created_by_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=225, null=True)),
                ('cover_letter', models.CharField(max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.companydetails')),
                ('created_by_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.agent')),
            ],
        ),
    ]
