# Generated by Django 3.2.8 on 2021-10-30 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0024_agentapply_agentask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='uploads/')),
                ('title', models.CharField(max_length=500)),
                ('discription', models.TextField(max_length=2500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('task_for_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect_app.agent')),
            ],
        ),
    ]
