# Generated by Django 3.2.8 on 2021-10-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0025_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Training',
        ),
    ]
