# Generated by Django 3.2.8 on 2021-10-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0026_rename_task_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='video',
        ),
        migrations.AddField(
            model_name='training',
            name='video_link',
            field=models.URLField(max_length=550, null=True),
        ),
    ]
