# Generated by Django 3.2.8 on 2021-10-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0027_auto_20211030_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdetails',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agentdetails',
            name='prof_img',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='agentdetails',
            name='short_summary',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='agentdetails',
            name='skype',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agentdetails',
            name='web_site',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
